production:
 adapter: postgresql
 encoding: unicode
 database: the_headphone_list_production
 pool: 5

development:
 adapter: postgresql
 encoding: unicode
 database: the_headphone_list_development
 pool: 5

test:
 adapter: postgresql
 encoding: unicode
 database: the_headphone_list_test
 pool: 5
